#!/bin/bash
# dzen2 pop
# 2007, by Robert Manea
#

TODAY=$(expr `date +'%d'` + 0)
MONTH=`date +'%m'`
YEAR=`date +'%Y'`
LINES=$(cal -m | wc -l)
LINES=$((LINES + 1))

(
#date +'%A, %d %b %Y %H:%M'
date +'^bg(#130F1C) '
date +''
# current month, highlight header and today
cal -m | sed -r -e "1,2 s/.*/^fg(#737373)&^fg()/"  -e "s/(^| )($TODAY)($| )/\1^bg(#596b79)^fg(#b5b5b5)\2^fg()^bg()\3/") | dzen2 -fn lemon -x 1320 -y 0 -w 170 -h 12 -l $LINES -sa c -p -e 'onstart=uncollapse,hide;button1=exit;' -fg "#909090" -bg "#0e1116" -tw 6
)


