#!/bin/bash
# dzen2 battery display by twily
#

while true; do
	BAT=$(((acpi -b | awk '/^Battery/ { print $4 }') | sed 's/%//g') | sed 's/,//g')

    TXT="$BAT %"
    if [ $BAT -eq 100 ]; then TXT="MAX"; elif [ $BAT -eq 0 ]; then TXT="MIN"; fi

    echo "^bg(#0D0D0D) "
    echo -ne "^cs()\n\n"
    
    if [ $BAT -gt 95 ]; then
        for i in {$(seq 1 20)}; do echo "●"; done
    elif [ $BAT -lt 5 ]; then
        for i in {$(seq 1 20)}; do echo "^fg(#3B3B3B█)"; done
    else
        for i in {$(seq 1 $(echo '20-('$BAT'/5)'|bc)); do echo "^fg(#3B3B3B)●"; done; for i in $(seq $(echo '20-(('$BAT'/5)-1)'|bc) 20); do echo "●"; done
    fi
    
    echo -e "\n^fg(#8c8c8c)$TXT\n"

	sleep 1;
done | dzen2 -sa c -w 48 -h 9 -fn lemon -y 0 -x 1174 -fg '#8c8c8c' -e "onstart=uncollapse,hide;button1=exit;" -l 24 -tw 6 -bg '#0e1116'

