#! /bin/bash
#
# Example panel for LemonBoy's bar

. panel_colors


num_mon=$(bspc query -M | wc -l)


# Colorscheme for mocho
#BLUE="#FF8AB3B5"
#RED="#FFCB6077"
#YELLOW="#FFF4BC87"
#ORANGE="#FFD28B71"
#MAGENTA="#FFA89BB9"
#TEAL="#FF7BBdA4"
#LIGHTGREY="#FFb8AfAD"
#DARKGREY="#FF7E705A"
#GREEN="#FF90A950"
#BG="#FF3B3228"


# Colorscheme for default-dark
BLUE="#FF6A9FB5"
RED="#FFAC4142"
YELLOW="#FF090909"
ORANGE="#FFFFFFFF"
MAGENTA="#FFAA759F"
TEAL="#FFAAAAAA"
LIGHTGREY="#FFB0B0B0"
DARKGREY="#FF505050"
GREEN="#FF99CC99"
PURPLE="#FF9547C9"
BG="#FF0e1116"
AC='%{A:'
AB=':}'
AE='%{A}'

#front="⮗ Axioen"

MIDDLE="#FF0e1116"

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#?}"
			;;
		T*)
			# xtitle output
			# prevents titles from overshooting
			# my tag layout in the middle
			formatted=$(echo ${line#?} | cut -c1-85)
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_STATUS_BG}$formatted"
			;;
		E*)
			userInfo="${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in

					M*)

						# active monitor
						if [ $num_mon -gt 1 ] ; then
						wm_infos="${wm_infos}%{F$COLOR_ACTIVE_MONITOR_FG}%{B$COLOR_ACTIVE_MONITOR_BG} ${name} %{B-}%{F-} %{A}"
					fi
					;;

					m*)

					# inactive monitor
						if [ $num_mon -gt 1 ] ; then
						wm_infos="${wm_infos}%{F$COLOR_INACTIVE_MONITOR_FG}%{B$COLOR_INACTIVE_MONITOR_BG} ${name} %{B-}%{F-} %{A}"
					fi
					;;

					O*)

					# focused occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
					;;

					F*)

					# focused free desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
					;;

					U*)

					# focused urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}%{U$COLOR_FOREGROUND}%{+u} ${name} %{-u}%{B-}%{F-}"
					;;

					o*)

					# occupied desktop
						wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG} ${name} %{B-}%{F-}"
					;;

					f*)

					# free desktop
						wm_infos="${wm_infos}%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG} ${name} %{B-}%{F-}"
					;;
			
					u*)

					# urgent desktop
						wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG} ${name} %{B-}%{F-}"
					;;


				esac
				shift
			done
			;;


	esac
	printf "%s\n" "%{l}${front}${wm_infos}%{B$BG} %{F$TEAL}$title %{l} %{r}$sys_infos "
done
